# Generated by Django 5.2.6 on 2025-09-09 06:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, validators=[users.models.validate_permissions]),
        ),
    ]
