# Generated by Django 5.2.6 on 2025-09-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD_VIDEO', 'Upload video'), ('WATCH_VIDEO', 'Watch video'), ('UPDATE_PROFILE', 'Update profile'), ('CHANGE_PASSWORD', 'Change password')], max_length=50),
        ),
    ]
